# theme
#include tokyo-night-moon.conf
#include rose-pine.conf
#include rose-pine-moon.conf
#include rose-pine-dawn.conf
#include Carbonfox.conf
#include Ayu.conf
include Bliss.conf

# font
# font_family      FiraCode Nerd Font
font_family      JetBrains Mono NL
font_size        12.0
bold_font        auto
italic_font      auto
bold_italic_font auto

cursor_shape     block
shell_integration enabled no-cursor

# background
background_opacity 0.90

# behaviour
confirm_os_window_close 0
