# Smart borders
windowrule = border_size 0, match:float 0, match:workspace w[tv1]
windowrule = border_size 0, match:float 0, match:workspace f[1]

windowrule {
    name = centered-window
    match:class = centered

    float = true
    min_size = 800 650
    max_size = 800 650
}

windowrule {
    name = terminal
    match:class = kitty
}

# Workspaces
windowrule = match:class firefox, workspace 2
windowrule = match:class code-oss, workspace 3
windowrule = match:class obsidian, workspace 3
windowrule = match:class org.telegram.desktop, workspace 4
windowrule = match:class mpv, workspace 4

# Apps
windowrule = float true, match:class org.*
windowrule = float true, match:class xdg-desktop-portal-gtk
